apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notes-api.fullname" . }}-config
  labels:
    {{- include "notes-api.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ include "notes-api.postgresFullname" . | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
